sudo: required
services:
  - docker

before_install:
  - docker build -t jazzrose/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jazzrose/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-445718290187"
  bucket_path: "docker-react"
  on:
    branch: main
access_key_id: "$AWS_ACCEESS_KEY"
secret_access_key: "$AWS_SECRET_KEY"
